### ISSUE TITLE
Provide link to settings files

### ISSUE THREAD

**Issue by NiallDarwin** [lijon/BafangWebConfig#10]
Provide link to settings files / suggestions for which settings are the ones to be careful of to avoid frying the controller.

**Comment by lijon** [comment]
I don't have any specific knowledge of which settings to be careful with. There are many posts online about these settings, and I suggest searching there instead.

**Comment by NiallDarwin** [comment]
Understood.
My experience is the same-everytime I tweak settings I spend a while searching online for advice. In the same way as your software makes it much quicker & easier to reprogram the motors, adding some links to posts with settings info can make finding the information easier.
I wanted to label this as 'gold plating' because its a nice to have not a problem or bug.
Thank you for the program :)

**Comment by lijon** [comment]
Feel free to provide a list of links to such useful pages about the settings, and I can include it in the README here :)
